apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
type: Opaque
data:
    username: YWRtaW4=                              #admin
    password: cGFzc3dvcmQ=                      #password


pv_pvc_mongodb.yml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu/mongo/mongo-vol           #create a folder using mkdir mongo/mongo-vol

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

